/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface BasicLoanDto {
  id: string;
  totalAmount: number;
  amount: number;
  interest: number;
  dateTime: string;
  name: string;
}
