/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LastPayment } from './lastPayment';
import { PersonDto } from './personDto';
import { CompanyDto } from './companyDto';


export interface BorrowerClientInformation { 
    id: string;
    person: PersonDto;
    displayName: string;
    company: CompanyDto;
    totalAmountLoaned: number;
    outstandingAmount: number;
    lastPayments: Array<LastPayment>;
}

