/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanAndPaymentDto } from './loanAndPaymentDto';
import { PersonDto } from './personDto';
import { CompanyDto } from './companyDto';

export interface BorrowerClientWithActiveLoansDto {
  id: string;
  person: PersonDto;
  displayName: string;
  company: CompanyDto;
  loans: LoanAndPaymentDto[];
}
