/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InOutBalanceType } from './inOutBalanceType';

export interface InOutBalanceDto {
  id?: string | null;
  date: string;
  amount: number;
  description: string;
  companyId: string;
  inOutBalanceType: InOutBalanceType;
}
export namespace InOutBalanceDto {}
