/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const InOutBalanceType = {
    Ingress: 'Ingress',
    Egress: 'Egress'
} as const;
export type InOutBalanceType = typeof InOutBalanceType[keyof typeof InOutBalanceType];

