/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type InOutBalanceType = 'Ingress' | 'Egress';

export const InOutBalanceType = {
  Ingress: 'Ingress' as InOutBalanceType,
  Egress: 'Egress' as InOutBalanceType,
};
