/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanStatus } from './loanStatus';


export interface LastPayment { 
    loanId: string;
    loanAmount: number;
    paymentAmount?: number | null;
    dateTime?: string | null;
    loanStatus: LoanStatus;
}
export namespace LastPayment {
}


