/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanType } from './loanType';
import { SimplePayments } from './simplePayments';
import { LoanStatus } from './loanStatus';
import { PaymentStatus } from './paymentStatus';

export interface LoanAndPaymentDto {
  id: string;
  borrowerClientId: string;
  amount: number;
  interest: number;
  dateTime: string;
  numberDate: number;
  loanType: LoanType;
  totalPayment: number;
  totalAmount: number;
  payments: SimplePayments[];
  loanStatus: LoanStatus;
  todayPaymentStatus: PaymentStatus;
  progressPercentage: number;
}
export namespace LoanAndPaymentDto {}
