/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type LoanStatus = 'New' | 'Active' | 'Finished' | 'Overdue';

export const LoanStatus = {
  New: 'New' as LoanStatus,
  Active: 'Active' as LoanStatus,
  Finished: 'Finished' as LoanStatus,
  Overdue: 'Overdue' as LoanStatus,
};
