/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type LoanType = 'Daily' | 'Weekly' | 'Monthly';

export const LoanType = {
  Daily: 'Daily' as LoanType,
  Weekly: 'Weekly' as LoanType,
  Monthly: 'Monthly' as LoanType,
};
