/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanType } from './loanType';

export interface LoanDto {
  id: string;
  amount: number;
  interest: number;
  dateTime: string;
  numberDate: number;
  loanType: LoanType;
  suggestedDays: string[];
  totalAmount: number;
  borrowerClientId: string;
}
export namespace LoanDto {}
