/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const LoanStatus = {
    New: 'New',
    Active: 'Active',
    Finished: 'Finished',
    Overdue: 'Overdue'
} as const;
export type LoanStatus = typeof LoanStatus[keyof typeof LoanStatus];

