/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type PaymentStatus = 'Paid' | 'Pending';

export const PaymentStatus = {
  Paid: 'Paid' as PaymentStatus,
  Pending: 'Pending' as PaymentStatus,
};
