/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PointDto } from './pointDto';

export interface PaymentDto {
  id: string;
  dateTime: string;
  amount: number;
  location: PointDto;
  isYape: boolean;
  number: number;
  loanId: string;
}
