/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PaymentStatus = {
    Paid: 'Paid',
    Pending: 'Pending'
} as const;
export type PaymentStatus = typeof PaymentStatus[keyof typeof PaymentStatus];

