/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PaymentDetailsResponseDto {
  id: string;
  name: string;
  dni: string;
  loanAmount: number;
  loanTotalAmount: number;
  paymentAmount: number;
  paymentDate: string;
  paymentNumber: number;
  paymentSum: number;
  url?: string | null;
}
