/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BorrowerClientWithActiveLoansDto } from './borrowerClientWithActiveLoansDto';

export interface PaymentResponseDto {
  borrowerClientWithActiveLoansDto: BorrowerClientWithActiveLoansDto;
  paymentId: string;
}
