/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimplePaymentDto } from './simplePaymentDto';
import { InOutBalanceDto } from './inOutBalanceDto';
import { BasicLoanDto } from './basicLoanDto';


export interface PaymentByDayReportResponseDto { 
    date: string;
    companyNames: Array<string>;
    loans: Array<BasicLoanDto>;
    simplePaymentDtos: Array<SimplePaymentDto>;
    inOutBalanceDtos: Array<InOutBalanceDto>;
}

