/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PersonDto {
  name: string;
  dni: string;
  phoneNumber: string;
  birthday?: string | null;
  address?: string | null;
  notes?: string | null;
}
