/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ReniecPersonalInformationDto {
  firstNames: string;
  fatherLastName: string;
  motherLastName: string;
  fullName: string;
  documentType: string;
  documentNumber: string;
  verificationDigit: string;
  exist: boolean;
}
