/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermissionDto } from './permissionDto';

export interface RoleDto {
  id: string;
  name: string;
  roles: RoleDto[];
  permissions: PermissionDto[];
}
