/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanType } from './loanType';


export interface SaveLoanDto { 
    id?: string | null;
    amount: number;
    interest: number;
    numberDate: number;
    loanType: LoanType;
    suggestedDays?: Array<string> | null;
    borrowerClientId: string;
    dateTime?: string | null;
}
export namespace SaveLoanDto {
}


