/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PointDto } from './pointDto';

export interface SavePaymentDto {
  id?: string | null;
  loanId: string;
  amount: number;
  isYape: boolean;
  location?: PointDto;
}
