/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserToRegister } from './userToRegister';
import { PersonDto } from './personDto';

export interface SaveUserDto {
  user: UserToRegister;
  createPersonDto: PersonDto;
  rolesId: string[];
  permissionsId: string[];
  companyIds: string[];
}
