/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SimplePaymentDto {
  name: string;
  amount: number;
  isYape: boolean;
  companyName: string;
}
