/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserToRegister {
  id?: string | null;
  email: string;
  isActive: boolean;
  password?: string | null;
  picture?: string | null;
}
