/**
 * MyAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDto } from './roleDto';
import { PermissionDto } from './permissionDto';
import { PersonDto } from './personDto';
import { CompanyDto } from './companyDto';

export interface UserDto {
  id: string;
  email: string;
  avatar?: string | null;
  background?: string | null;
  isActive: boolean;
  person: PersonDto;
  roles: RoleDto[];
  permissions: PermissionDto[];
  companies: CompanyDto[];
}
